package Telas.Tips;

import java.awt.event.KeyEvent;

public class JInternalTips extends javax.swing.JInternalFrame {

    public boolean bg1 = false;
    public boolean bg2 = false;
    public boolean bg3 = false;
        public boolean b1 = false;
        public boolean b2 = false;
        public boolean b3 = false;
        public boolean b4 = false;
    public boolean bg4 = false;
        public boolean bg41 = false;
        public boolean bg42 = false;
        public boolean bg43 = false;
        public boolean bg44 = false;
    public boolean bg5 = false;
        public boolean bg51 = false;
        public boolean bg52 = false;
    public boolean bg6 = false;
        public boolean bg61 = false;
    public boolean bg7 = false;

    public JInternalTips() {
        initComponents();
        // x    y
        setSize(912, 575);
        verificarDica("bg1");
        jbInicio.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbPTI12 = new javax.swing.JButton();
        jbATI12 = new javax.swing.JButton();
        jbTMAConfig = new javax.swing.JButton();
        jbPTI11 = new javax.swing.JButton();
        jbATI11 = new javax.swing.JButton();
        jbTMAResultado2 = new javax.swing.JButton();
        jbATI10 = new javax.swing.JButton();
        jbPTI10 = new javax.swing.JButton();
        jbTMAResultado1 = new javax.swing.JButton();
        jbATI9 = new javax.swing.JButton();
        jbPTI9 = new javax.swing.JButton();
        jbTMACandidato3 = new javax.swing.JButton();
        jbATI8 = new javax.swing.JButton();
        jbPTI8 = new javax.swing.JButton();
        jbTMACandidato2 = new javax.swing.JButton();
        jbATI7 = new javax.swing.JButton();
        jbPTI7 = new javax.swing.JButton();
        jbTMACandidato1 = new javax.swing.JButton();
        jbATI6 = new javax.swing.JButton();
        jbPTI6 = new javax.swing.JButton();
        jbTMAEleicao5 = new javax.swing.JButton();
        jbATI5 = new javax.swing.JButton();
        jbPTI5 = new javax.swing.JButton();
        jbTMAEleicao4 = new javax.swing.JButton();
        jbATI4 = new javax.swing.JButton();
        jbPTI4 = new javax.swing.JButton();
        jbTMAEleicao3 = new javax.swing.JButton();
        jbATI3 = new javax.swing.JButton();
        jbPTI3 = new javax.swing.JButton();
        jbTMAEleicao2 = new javax.swing.JButton();
        jbATI2 = new javax.swing.JButton();
        jbPTI2 = new javax.swing.JButton();
        jbTMAEleicao1 = new javax.swing.JButton();
        jbEleicao = new javax.swing.JButton();
        jbCandidato = new javax.swing.JButton();
        jbResultado = new javax.swing.JButton();
        jbConfig = new javax.swing.JButton();
        lbEleicao = new javax.swing.JLabel();
        lbCandidatos = new javax.swing.JLabel();
        lbResultado = new javax.swing.JLabel();
        lbConfig = new javax.swing.JLabel();
        jbTMenuAjuda = new javax.swing.JButton();
        jbATI = new javax.swing.JButton();
        jbPTI = new javax.swing.JButton();
        jbTTelaInicial = new javax.swing.JButton();
        jbInicio = new javax.swing.JButton();

        setClosable(true);
        setTitle("Ajudas e dicas sobre o sistema de eleição");
        getContentPane().setLayout(null);

        jbPTI12.setContentAreaFilled(false);
        jbPTI12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPTI12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPTI12ActionPerformed(evt);
            }
        });
        getContentPane().add(jbPTI12);
        jbPTI12.setBounds(240, 480, 220, 50);

        jbATI12.setContentAreaFilled(false);
        jbATI12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbATI12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbATI12ActionPerformed(evt);
            }
        });
        getContentPane().add(jbATI12);
        jbATI12.setBounds(30, 480, 140, 50);

        jbTMAConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMAConfig.png"))); // NOI18N
        jbTMAConfig.setContentAreaFilled(false);
        jbTMAConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbTMAConfig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTMAConfigKeyPressed(evt);
            }
        });
        getContentPane().add(jbTMAConfig);
        jbTMAConfig.setBounds(0, 0, 900, 550);

        jbPTI11.setContentAreaFilled(false);
        jbPTI11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPTI11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPTI11ActionPerformed(evt);
            }
        });
        getContentPane().add(jbPTI11);
        jbPTI11.setBounds(230, 480, 240, 50);

        jbATI11.setContentAreaFilled(false);
        jbATI11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbATI11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbATI11ActionPerformed(evt);
            }
        });
        getContentPane().add(jbATI11);
        jbATI11.setBounds(30, 480, 140, 50);

        jbTMAResultado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMAResultado2.png"))); // NOI18N
        jbTMAResultado2.setContentAreaFilled(false);
        jbTMAResultado2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbTMAResultado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTMAResultado2KeyPressed(evt);
            }
        });
        getContentPane().add(jbTMAResultado2);
        jbTMAResultado2.setBounds(0, 0, 900, 550);

        jbATI10.setContentAreaFilled(false);
        jbATI10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbATI10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbATI10ActionPerformed(evt);
            }
        });
        getContentPane().add(jbATI10);
        jbATI10.setBounds(30, 480, 140, 50);

        jbPTI10.setContentAreaFilled(false);
        jbPTI10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPTI10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPTI10ActionPerformed(evt);
            }
        });
        getContentPane().add(jbPTI10);
        jbPTI10.setBounds(620, 480, 240, 50);

        jbTMAResultado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMAResultado1.png"))); // NOI18N
        jbTMAResultado1.setContentAreaFilled(false);
        jbTMAResultado1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbTMAResultado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTMAResultado1KeyPressed(evt);
            }
        });
        getContentPane().add(jbTMAResultado1);
        jbTMAResultado1.setBounds(0, 0, 900, 550);

        jbATI9.setContentAreaFilled(false);
        jbATI9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbATI9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbATI9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbATI9);
        jbATI9.setBounds(30, 480, 140, 50);

        jbPTI9.setContentAreaFilled(false);
        jbPTI9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPTI9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPTI9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbPTI9);
        jbPTI9.setBounds(620, 480, 240, 50);

        jbTMACandidato3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMACandidato3.png"))); // NOI18N
        jbTMACandidato3.setContentAreaFilled(false);
        jbTMACandidato3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbTMACandidato3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTMACandidato3KeyPressed(evt);
            }
        });
        getContentPane().add(jbTMACandidato3);
        jbTMACandidato3.setBounds(0, 0, 900, 550);

        jbATI8.setContentAreaFilled(false);
        jbATI8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbATI8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbATI8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbATI8);
        jbATI8.setBounds(30, 480, 140, 50);

        jbPTI8.setContentAreaFilled(false);
        jbPTI8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPTI8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPTI8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbPTI8);
        jbPTI8.setBounds(250, 480, 150, 50);

        jbTMACandidato2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMACandidato2.png"))); // NOI18N
        jbTMACandidato2.setContentAreaFilled(false);
        jbTMACandidato2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbTMACandidato2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTMACandidato2KeyPressed(evt);
            }
        });
        getContentPane().add(jbTMACandidato2);
        jbTMACandidato2.setBounds(0, 0, 900, 550);

        jbATI7.setContentAreaFilled(false);
        jbATI7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbATI7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbATI7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbATI7);
        jbATI7.setBounds(30, 480, 140, 50);

        jbPTI7.setContentAreaFilled(false);
        jbPTI7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPTI7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPTI7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbPTI7);
        jbPTI7.setBounds(250, 480, 150, 50);

        jbTMACandidato1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMACandidato1.png"))); // NOI18N
        jbTMACandidato1.setContentAreaFilled(false);
        jbTMACandidato1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbTMACandidato1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTMACandidato1KeyPressed(evt);
            }
        });
        getContentPane().add(jbTMACandidato1);
        jbTMACandidato1.setBounds(0, 0, 900, 550);

        jbATI6.setContentAreaFilled(false);
        jbATI6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbATI6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbATI6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbATI6);
        jbATI6.setBounds(30, 480, 140, 50);

        jbPTI6.setContentAreaFilled(false);
        jbPTI6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPTI6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPTI6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbPTI6);
        jbPTI6.setBounds(600, 480, 260, 50);

        jbTMAEleicao5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMAEleicao5.png"))); // NOI18N
        jbTMAEleicao5.setContentAreaFilled(false);
        jbTMAEleicao5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbTMAEleicao5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTMAEleicao5KeyPressed(evt);
            }
        });
        getContentPane().add(jbTMAEleicao5);
        jbTMAEleicao5.setBounds(0, 0, 900, 550);

        jbATI5.setContentAreaFilled(false);
        jbATI5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbATI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbATI5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbATI5);
        jbATI5.setBounds(30, 480, 140, 50);

        jbPTI5.setContentAreaFilled(false);
        jbPTI5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPTI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPTI5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbPTI5);
        jbPTI5.setBounds(260, 480, 140, 50);

        jbTMAEleicao4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMAEleicao4.png"))); // NOI18N
        jbTMAEleicao4.setContentAreaFilled(false);
        jbTMAEleicao4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbTMAEleicao4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTMAEleicao4KeyPressed(evt);
            }
        });
        getContentPane().add(jbTMAEleicao4);
        jbTMAEleicao4.setBounds(0, 0, 900, 550);

        jbATI4.setContentAreaFilled(false);
        jbATI4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbATI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbATI4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbATI4);
        jbATI4.setBounds(30, 480, 140, 50);

        jbPTI4.setContentAreaFilled(false);
        jbPTI4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPTI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPTI4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbPTI4);
        jbPTI4.setBounds(260, 480, 140, 50);

        jbTMAEleicao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMAEleicao3.png"))); // NOI18N
        jbTMAEleicao3.setContentAreaFilled(false);
        jbTMAEleicao3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbTMAEleicao3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTMAEleicao3KeyPressed(evt);
            }
        });
        getContentPane().add(jbTMAEleicao3);
        jbTMAEleicao3.setBounds(0, 0, 900, 550);

        jbATI3.setContentAreaFilled(false);
        jbATI3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbATI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbATI3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbATI3);
        jbATI3.setBounds(30, 480, 140, 50);

        jbPTI3.setContentAreaFilled(false);
        jbPTI3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPTI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPTI3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbPTI3);
        jbPTI3.setBounds(260, 480, 140, 50);

        jbTMAEleicao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMAEleicao2.png"))); // NOI18N
        jbTMAEleicao2.setContentAreaFilled(false);
        jbTMAEleicao2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbTMAEleicao2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTMAEleicao2KeyPressed(evt);
            }
        });
        getContentPane().add(jbTMAEleicao2);
        jbTMAEleicao2.setBounds(0, 0, 900, 550);

        jbATI2.setContentAreaFilled(false);
        jbATI2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbATI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbATI2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbATI2);
        jbATI2.setBounds(30, 480, 140, 50);

        jbPTI2.setContentAreaFilled(false);
        jbPTI2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPTI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPTI2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbPTI2);
        jbPTI2.setBounds(260, 480, 140, 50);

        jbTMAEleicao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMAEleicao1.png"))); // NOI18N
        jbTMAEleicao1.setContentAreaFilled(false);
        jbTMAEleicao1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbTMAEleicao1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTMAEleicao1KeyPressed(evt);
            }
        });
        getContentPane().add(jbTMAEleicao1);
        jbTMAEleicao1.setBounds(0, 0, 900, 550);

        jbEleicao.setContentAreaFilled(false);
        jbEleicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbEleicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEleicaoActionPerformed(evt);
            }
        });
        jbEleicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbEleicaoKeyPressed(evt);
            }
        });
        getContentPane().add(jbEleicao);
        jbEleicao.setBounds(60, 160, 330, 120);

        jbCandidato.setContentAreaFilled(false);
        jbCandidato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCandidatoActionPerformed(evt);
            }
        });
        jbCandidato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCandidatoKeyPressed(evt);
            }
        });
        getContentPane().add(jbCandidato);
        jbCandidato.setBounds(510, 160, 330, 120);

        jbResultado.setContentAreaFilled(false);
        jbResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbResultadoActionPerformed(evt);
            }
        });
        jbResultado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbResultadoKeyPressed(evt);
            }
        });
        getContentPane().add(jbResultado);
        jbResultado.setBounds(60, 360, 330, 120);

        jbConfig.setContentAreaFilled(false);
        jbConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfigActionPerformed(evt);
            }
        });
        jbConfig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbConfigKeyPressed(evt);
            }
        });
        getContentPane().add(jbConfig);
        jbConfig.setBounds(510, 360, 330, 120);

        lbEleicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMenuAjudaBotao.png"))); // NOI18N
        lbEleicao.setText("jLabel1");
        getContentPane().add(lbEleicao);
        lbEleicao.setBounds(50, 140, 350, 150);

        lbCandidatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMenuAjudaBotao.png"))); // NOI18N
        lbCandidatos.setText("jLabel1");
        getContentPane().add(lbCandidatos);
        lbCandidatos.setBounds(500, 140, 350, 150);

        lbResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMenuAjudaBotao.png"))); // NOI18N
        lbResultado.setText("jLabel1");
        getContentPane().add(lbResultado);
        lbResultado.setBounds(50, 340, 350, 150);

        lbConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMenuAjudaBotao.png"))); // NOI18N
        lbConfig.setText("jLabel1");
        getContentPane().add(lbConfig);
        lbConfig.setBounds(510, 340, 350, 150);

        jbTMenuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTMenuAjuda.png"))); // NOI18N
        jbTMenuAjuda.setContentAreaFilled(false);
        jbTMenuAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbTMenuAjuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTMenuAjudaKeyPressed(evt);
            }
        });
        getContentPane().add(jbTMenuAjuda);
        jbTMenuAjuda.setBounds(0, 0, 900, 550);

        jbATI.setContentAreaFilled(false);
        jbATI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbATI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbATIActionPerformed(evt);
            }
        });
        getContentPane().add(jbATI);
        jbATI.setBounds(120, 20, 120, 50);

        jbPTI.setContentAreaFilled(false);
        jbPTI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPTIActionPerformed(evt);
            }
        });
        getContentPane().add(jbPTI);
        jbPTI.setBounds(690, 20, 120, 50);

        jbTTelaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTTelaInicial.png"))); // NOI18N
        jbTTelaInicial.setContentAreaFilled(false);
        jbTTelaInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbTTelaInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbTTelaInicialKeyPressed(evt);
            }
        });
        getContentPane().add(jbTTelaInicial);
        jbTTelaInicial.setBounds(0, 0, 900, 550);

        jbInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Tips/bgTips.png"))); // NOI18N
        jbInicio.setContentAreaFilled(false);
        jbInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbInicioKeyPressed(evt);
            }
        });
        getContentPane().add(jbInicio);
        jbInicio.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbInicioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificarDica("bg2");
            jbTTelaInicial.requestFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            verificarDica("bg2");
            jbTTelaInicial.requestFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbInicioKeyPressed

    private void jbTTelaInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTTelaInicialKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            verificarDica("bg1");
            jbInicio.requestFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            b1 = true;
            verificarDica("bg3");
            jbEleicao.requestFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbTTelaInicialKeyPressed

//----------------------Menu----------------------------------------------------      
    private void jbTMenuAjudaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTMenuAjudaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            verificarDica("bg2");
            jbTTelaInicial.requestFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbTMenuAjudaKeyPressed

    private void jbATIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbATIActionPerformed
        verificarDica("bg1");
        jbInicio.requestFocus();
    }//GEN-LAST:event_jbATIActionPerformed

    private void jbPTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPTIActionPerformed
        b1 = true;
        verificarDica("bg3");
        jbTMenuAjuda.requestFocus();
    }//GEN-LAST:event_jbPTIActionPerformed

    private void jbEleicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEleicaoActionPerformed
        jbTMAEleicao1.requestFocus();
        verificarDica("bg4");
    }//GEN-LAST:event_jbEleicaoActionPerformed

    private void jbCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCandidatoActionPerformed
        jbTMACandidato1.requestFocus();
        verificarDica("bg5");
    }//GEN-LAST:event_jbCandidatoActionPerformed

    private void jbResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbResultadoActionPerformed
        jbTMAResultado1.requestFocus();
        verificarDica("bg6");
    }//GEN-LAST:event_jbResultadoActionPerformed

    private void jbConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfigActionPerformed
        jbTMAConfig.requestFocus();
        verificarDica("bg7");
    }//GEN-LAST:event_jbConfigActionPerformed
//----------------------Menu----------------------------------------------------  
    
    
//----------------------Eleição-------------------------------------------------    
    private void jbEleicaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbEleicaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificarDica("bg4");
        }

        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            verificarDica("bg2");
            jbTTelaInicial.requestFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            b2 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            b3 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbEleicaoKeyPressed

    private void jbCandidatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCandidatoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificarDica("bg5");
        }

        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            b1 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            b4 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbCandidatoKeyPressed

    private void jbResultadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbResultadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificarDica("bg6");
        }

        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            verificarDica("bg2");
            jbTTelaInicial.requestFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            b4 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            b1 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbResultadoKeyPressed

    private void jbConfigKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbConfigKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbTMAConfig.requestFocus();
            verificarDica("bg7");
        }

        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            b3 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            b2 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbConfigKeyPressed

    private void jbTMAEleicao1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTMAEleicao1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            b1 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            verificarDica("bg41");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbTMAEleicao1KeyPressed

    private void jbPTI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPTI2ActionPerformed
        verificarDica("bg41");
    }//GEN-LAST:event_jbPTI2ActionPerformed

    private void jbATI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbATI2ActionPerformed
        b1 = true;
        verificarDica("bg3");
    }//GEN-LAST:event_jbATI2ActionPerformed

    private void jbTMAEleicao2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTMAEleicao2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            verificarDica("bg4");
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            verificarDica("bg42");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbTMAEleicao2KeyPressed

    private void jbATI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbATI3ActionPerformed
        verificarDica("bg4");
    }//GEN-LAST:event_jbATI3ActionPerformed

    private void jbPTI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPTI3ActionPerformed
        verificarDica("bg42");
    }//GEN-LAST:event_jbPTI3ActionPerformed

    private void jbATI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbATI4ActionPerformed
        verificarDica("bg41");
    }//GEN-LAST:event_jbATI4ActionPerformed

    private void jbPTI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPTI4ActionPerformed
        verificarDica("bg42");
    }//GEN-LAST:event_jbPTI4ActionPerformed

    private void jbTMAEleicao3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTMAEleicao3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            verificarDica("bg41");
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            verificarDica("bg43");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbTMAEleicao3KeyPressed

    private void jbATI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbATI5ActionPerformed
        verificarDica("bg42");
    }//GEN-LAST:event_jbATI5ActionPerformed

    private void jbPTI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPTI5ActionPerformed
        verificarDica("bg44");
    }//GEN-LAST:event_jbPTI5ActionPerformed

    private void jbTMAEleicao4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTMAEleicao4KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            verificarDica("bg42");
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            verificarDica("bg44");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbTMAEleicao4KeyPressed

    private void jbATI6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbATI6ActionPerformed
        verificarDica("bg43");
    }//GEN-LAST:event_jbATI6ActionPerformed

    private void jbPTI6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPTI6ActionPerformed
        b1 = true;
        verificarDica("bg3");
    }//GEN-LAST:event_jbPTI6ActionPerformed

    private void jbTMAEleicao5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTMAEleicao5KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            verificarDica("bg43");
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            b1 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbTMAEleicao5KeyPressed
//----------------------Eleição-------------------------------------------------

    
//----------------------Candidatos----------------------------------------------    
    private void jbATI7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbATI7ActionPerformed
        b1 = true;
        verificarDica("bg3");
    }//GEN-LAST:event_jbATI7ActionPerformed

    private void jbPTI7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPTI7ActionPerformed
        verificarDica("bg51");
    }//GEN-LAST:event_jbPTI7ActionPerformed

    private void jbTMACandidato1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTMACandidato1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            b1 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            verificarDica("bg51");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbTMACandidato1KeyPressed

    private void jbATI8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbATI8ActionPerformed
        verificarDica("bg51");
    }//GEN-LAST:event_jbATI8ActionPerformed

    private void jbPTI8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPTI8ActionPerformed
        verificarDica("bg52");
    }//GEN-LAST:event_jbPTI8ActionPerformed

    private void jbTMACandidato2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTMACandidato2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            verificarDica("bg5");
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            verificarDica("bg52");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbTMACandidato2KeyPressed

    private void jbATI9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbATI9ActionPerformed
        verificarDica("bg51");
    }//GEN-LAST:event_jbATI9ActionPerformed

    private void jbPTI9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPTI9ActionPerformed
        b1 = true;
        verificarDica("bg3");
    }//GEN-LAST:event_jbPTI9ActionPerformed

    private void jbTMACandidato3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTMACandidato3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            verificarDica("bg51");
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            b1 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbTMACandidato3KeyPressed
//----------------------Candidatos----------------------------------------------  

    
//----------------------Resultado-----------------------------------------------      
    private void jbATI10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbATI10ActionPerformed
        b1 = true;
        verificarDica("bg3");
    }//GEN-LAST:event_jbATI10ActionPerformed

    private void jbPTI10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPTI10ActionPerformed
        verificarDica("bg61");
    }//GEN-LAST:event_jbPTI10ActionPerformed

    private void jbTMAResultado1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTMAResultado1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            b1 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            verificarDica("bg61");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbTMAResultado1KeyPressed

    private void jbPTI11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPTI11ActionPerformed
        b1 = true;
        verificarDica("bg3");
    }//GEN-LAST:event_jbPTI11ActionPerformed

    private void jbATI11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbATI11ActionPerformed
        verificarDica("bg6");
    }//GEN-LAST:event_jbATI11ActionPerformed

    private void jbTMAResultado2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTMAResultado2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            verificarDica("bg6");
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            b1 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbTMAResultado2KeyPressed
//----------------------Resultado-----------------------------------------------
    
    
    private void jbPTI12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPTI12ActionPerformed
        b1=true;
        verificarDica("bg3");
    }//GEN-LAST:event_jbPTI12ActionPerformed

    private void jbATI12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbATI12ActionPerformed
        b1=true;
        verificarDica("bg3");
    }//GEN-LAST:event_jbATI12ActionPerformed

    private void jbTMAConfigKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbTMAConfigKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            b1=true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            b1 = true;
            verificarDica("bg3");
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jbTMAConfigKeyPressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbATI;
    private javax.swing.JButton jbATI10;
    private javax.swing.JButton jbATI11;
    private javax.swing.JButton jbATI12;
    private javax.swing.JButton jbATI2;
    private javax.swing.JButton jbATI3;
    private javax.swing.JButton jbATI4;
    private javax.swing.JButton jbATI5;
    private javax.swing.JButton jbATI6;
    private javax.swing.JButton jbATI7;
    private javax.swing.JButton jbATI8;
    private javax.swing.JButton jbATI9;
    private javax.swing.JButton jbCandidato;
    private javax.swing.JButton jbConfig;
    private javax.swing.JButton jbEleicao;
    private javax.swing.JButton jbInicio;
    private javax.swing.JButton jbPTI;
    private javax.swing.JButton jbPTI10;
    private javax.swing.JButton jbPTI11;
    private javax.swing.JButton jbPTI12;
    private javax.swing.JButton jbPTI2;
    private javax.swing.JButton jbPTI3;
    private javax.swing.JButton jbPTI4;
    private javax.swing.JButton jbPTI5;
    private javax.swing.JButton jbPTI6;
    private javax.swing.JButton jbPTI7;
    private javax.swing.JButton jbPTI8;
    private javax.swing.JButton jbPTI9;
    private javax.swing.JButton jbResultado;
    private javax.swing.JButton jbTMACandidato1;
    private javax.swing.JButton jbTMACandidato2;
    private javax.swing.JButton jbTMACandidato3;
    private javax.swing.JButton jbTMAConfig;
    private javax.swing.JButton jbTMAEleicao1;
    private javax.swing.JButton jbTMAEleicao2;
    private javax.swing.JButton jbTMAEleicao3;
    private javax.swing.JButton jbTMAEleicao4;
    private javax.swing.JButton jbTMAEleicao5;
    private javax.swing.JButton jbTMAResultado1;
    private javax.swing.JButton jbTMAResultado2;
    private javax.swing.JButton jbTMenuAjuda;
    private javax.swing.JButton jbTTelaInicial;
    private javax.swing.JLabel lbCandidatos;
    private javax.swing.JLabel lbConfig;
    private javax.swing.JLabel lbEleicao;
    private javax.swing.JLabel lbResultado;
    // End of variables declaration//GEN-END:variables

    private void verificarDica(String b) {
        jbInicio.setVisible(false); //1

        jbTTelaInicial.setVisible(false); //2
        jbATI.setVisible(false);
        jbPTI.setVisible(false);

        jbTMenuAjuda.setVisible(false); //3
        jbEleicao.setVisible(false);
        jbCandidato.setVisible(false);
        jbResultado.setVisible(false);
        jbConfig.setVisible(false);
        lbCandidatos.setVisible(false);
        lbConfig.setVisible(false);
        lbEleicao.setVisible(false);
        lbResultado.setVisible(false);

        jbTMAEleicao1.setVisible(false); //4
        jbATI2.setVisible(false);
        jbPTI2.setVisible(false);
        jbTMAEleicao2.setVisible(false);
        jbATI3.setVisible(false);
        jbPTI3.setVisible(false);
        jbTMAEleicao3.setVisible(false);
        jbATI4.setVisible(false);
        jbPTI4.setVisible(false);
        jbTMAEleicao4.setVisible(false);
        jbATI5.setVisible(false);
        jbPTI5.setVisible(false);
        jbTMAEleicao5.setVisible(false);
        jbATI6.setVisible(false);
        jbPTI6.setVisible(false);

        jbTMACandidato1.setVisible(false);
        jbATI7.setVisible(false);
        jbPTI7.setVisible(false);
        jbTMACandidato2.setVisible(false);
        jbATI8.setVisible(false);
        jbPTI8.setVisible(false);
        jbTMACandidato3.setVisible(false);
        jbATI9.setVisible(false);
        jbPTI9.setVisible(false);

        jbTMAResultado1.setVisible(false);
        jbATI10.setVisible(false);
        jbPTI10.setVisible(false);
        jbTMAResultado2.setVisible(false);
        jbATI11.setVisible(false);
        jbPTI11.setVisible(false);
        
        jbTMAConfig.setVisible(false);
        jbATI12.setVisible(false);
        jbPTI12.setVisible(false);
        //----------------------------------------------------------------------
        if (b.equalsIgnoreCase("bg1")) {
            bg1 = true;
        } else if (b.equalsIgnoreCase("bg2")) {
            bg2 = true;
        } else if (b.equalsIgnoreCase("bg3")) {
            bg3 = true;
            //----------------------------------------------------------------------    
        } else if (b.equalsIgnoreCase("bg4")) {
            bg4 = true;
            } else if (b.equalsIgnoreCase("bg41")) {
                bg41 = true;
            } else if (b.equalsIgnoreCase("bg42")) {
                bg42 = true;
            } else if (b.equalsIgnoreCase("bg43")) {
                bg43 = true;
            } else if (b.equalsIgnoreCase("bg44")) {
                bg44 = true;
        } else if (b.equalsIgnoreCase("bg5")) {
            bg5 = true;
            } else if (b.equalsIgnoreCase("bg51")) {
                bg51 = true;
            } else if (b.equalsIgnoreCase("bg52")) {
                bg52 = true;
            
        }else if (b.equalsIgnoreCase("bg6")) {
            bg6 = true;
            }else if (b.equalsIgnoreCase("bg61")) {
                bg61 = true; 
        }else if (b.equalsIgnoreCase("bg7")) {
            bg7 = true;
        }

        //----------------------------------------------------------------------
        if (bg1 == true) {
            jbInicio.setVisible(true);
        } else if (bg2 == true) {
            jbTTelaInicial.setVisible(true); //2
            jbATI.setVisible(true);
            jbPTI.setVisible(true);
        } else if (bg3 == true) {
            jbTMenuAjuda.setVisible(true); //3
            jbEleicao.setVisible(true);
            jbCandidato.setVisible(true);
            jbResultado.setVisible(true);
            jbConfig.setVisible(true);

            if (b1 == true) {
                lbEleicao.setVisible(true);
                jbEleicao.requestFocus();
            } else if (b2 == true) {
                lbCandidatos.setVisible(true);
                jbCandidato.requestFocus();
            } else if (b3 == true) {
                lbResultado.setVisible(true);
                jbResultado.requestFocus();
            } else if (b4 == true) {
                lbConfig.setVisible(true);
                jbConfig.requestFocus();
            }
            //----------------------------------------------------------------------
        } else if (bg4 == true) { //Eleição1
            jbTMAEleicao1.requestFocus();
            jbTMAEleicao1.setVisible(true); //4
            jbATI2.setVisible(true);
            jbPTI2.setVisible(true);
            } else if (bg41 == true) { //Eleição2
                jbTMAEleicao2.requestFocus();
                jbTMAEleicao2.setVisible(true); //4
                jbATI3.setVisible(true);
                jbPTI3.setVisible(true);
            } else if (bg42 == true) {
                jbTMAEleicao3.requestFocus();
                jbTMAEleicao3.setVisible(true); //4
                jbATI4.setVisible(true);
                jbPTI4.setVisible(true);
            } else if (bg43 == true) {
                jbTMAEleicao4.requestFocus();
                jbTMAEleicao4.setVisible(true); //4
                jbATI5.setVisible(true);
                jbPTI5.setVisible(true);
            }else if (bg44 == true) {
                jbTMAEleicao5.requestFocus();
                jbTMAEleicao5.setVisible(true); //4
                jbATI6.setVisible(true);
                jbPTI6.setVisible(true);
        }    
        //----------------------------------------------------------------------              
        else if (bg5 == true) {
            jbTMACandidato1.requestFocus();
            jbTMACandidato1.setVisible(true); //5
            jbATI7.setVisible(true);
            jbPTI7.setVisible(true);
            } else if (bg51 == true) {
                jbTMACandidato2.requestFocus();
                jbTMACandidato2.setVisible(true); //5
                jbATI8.setVisible(true);
                jbPTI8.setVisible(true);
            } else if (bg52 == true) {
                jbTMACandidato3.requestFocus();
                jbTMACandidato3.setVisible(true); //5
                jbATI9.setVisible(true);
                jbPTI9.setVisible(true);
        } 
        //----------------------------------------------------------------------
        else if (bg6 == true) {
            jbTMAResultado1.requestFocus();
            jbTMAResultado1.setVisible(true); //5
            jbATI10.setVisible(true);
            jbPTI10.setVisible(true);
        }else if (bg61 == true) {
            jbTMAResultado2.requestFocus();
            jbTMAResultado2.setVisible(true); //5
            jbATI11.setVisible(true);
            jbPTI11.setVisible(true);
        }
        //----------------------------------------------------------------------
        else if (bg7 == true) {
            jbTMAConfig.requestFocus();
            jbTMAConfig.setVisible(true); //5
            jbATI12.setVisible(true);
            jbPTI12.setVisible(true);
        }
        //----------------------------------------------------------------------
        
        
        
        
        
        
        bg1 = false;
        bg2 = false;
        bg3 = false;
            b1 = false;
            b2 = false;
            b3 = false;
            b4 = false;
        bg4 = false;
            bg41 = false;
            bg42 = false;
            bg43 = false;
            bg44 = false;
        bg5 = false;
            bg51 = false;
            bg52 = false;
        bg6 = false;
            bg61 = false;
        bg7 = false;

    }

}
