
package Telas.Votação;

import Telas.Cadastrar.*;
import Controles.Conexões.Conexao;
import Controles.DAOs.AdminDAO;
import Controles.DAOs.CandidatoDAO;
import Controles.DAOs.EleicaoDAO;
import Modelos.Candidato.Candidato;
import Modelos.Eleição.Eleicao;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class JInternalVotar extends javax.swing.JInternalFrame {

    public static String path = "";
    
    //--------------------------------------------------------------
    
    public boolean b1=false;
    public boolean b2=false;
    public boolean b3=false;
    public boolean b4=false;
    public boolean b5=false;
    public boolean b6=false;
    public boolean b7=false;
    public boolean b8=false;
    public boolean b9=false;
    public boolean b0=false;
    
    public boolean bBranco=false;
    public boolean bCorrigir=false;
    public boolean bVotar=false;

    //--------------------------------------------------------------
    
    public int sono = 4;
    
    URL url = JInternalVotar.class.getResource("/Sons/voto.wav");
    AudioClip audio = Applet.newAudioClip(url);
    
    public JInternalVotar() {
        initComponents();
        limparVotacao();
        setSize(901, 556);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbFoto = new javax.swing.JLabel();
        PainelDados1 = new javax.swing.JPanel();
        Codigo = new javax.swing.JLabel();
        jtfCod = new javax.swing.JLabel();
        PainelDados = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JLabel();
        PainelNumeros = new javax.swing.JPanel();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        jb7 = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jb0 = new javax.swing.JButton();
        Sel1 = new javax.swing.JLabel();
        Sel2 = new javax.swing.JLabel();
        Sel3 = new javax.swing.JLabel();
        Sel4 = new javax.swing.JLabel();
        Sel5 = new javax.swing.JLabel();
        Sel6 = new javax.swing.JLabel();
        Sel7 = new javax.swing.JLabel();
        Sel8 = new javax.swing.JLabel();
        Sel9 = new javax.swing.JLabel();
        Sel0 = new javax.swing.JLabel();
        PainelBotoes = new javax.swing.JPanel();
        jbBranco = new javax.swing.JButton();
        jbCorrigir = new javax.swing.JButton();
        jbVotar = new javax.swing.JButton();
        SelBr = new javax.swing.JLabel();
        SelCor = new javax.swing.JLabel();
        SelVot = new javax.swing.JLabel();
        lbUrna = new javax.swing.JLabel();
        jtfSenha = new javax.swing.JPasswordField();
        lbBranco = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Sala de votação");
        getContentPane().setLayout(null);
        getContentPane().add(lbFoto);
        lbFoto.setBounds(110, 100, 270, 280);

        PainelDados1.setBackground(new java.awt.Color(255, 255, 255));

        Codigo.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Codigo.setText("Número:");

        jtfCod.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jtfCod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PainelDados1Layout = new javax.swing.GroupLayout(PainelDados1);
        PainelDados1.setLayout(PainelDados1Layout);
        PainelDados1Layout.setHorizontalGroup(
            PainelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDados1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PainelDados1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jtfCod, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelDados1Layout.setVerticalGroup(
            PainelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDados1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCod, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        getContentPane().add(PainelDados1);
        PainelDados1.setBounds(400, 150, 170, 160);

        PainelDados.setBackground(new java.awt.Color(255, 255, 255));
        PainelDados.setOpaque(false);

        Nome.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Nome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nome.setText("Nome:");

        jtfNome.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        jtfNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PainelDadosLayout = new javax.swing.GroupLayout(PainelDados);
        PainelDados.setLayout(PainelDadosLayout);
        PainelDadosLayout.setHorizontalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelDadosLayout.setVerticalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDadosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(PainelDados);
        PainelDados.setBounds(70, 400, 340, 90);

        PainelNumeros.setOpaque(false);
        PainelNumeros.setLayout(null);

        jb1.setContentAreaFilled(false);
        jb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        jb1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb1KeyPressed(evt);
            }
        });
        PainelNumeros.add(jb1);
        jb1.setBounds(10, 15, 50, 50);

        jb2.setContentAreaFilled(false);
        jb2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        jb2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb2KeyPressed(evt);
            }
        });
        PainelNumeros.add(jb2);
        jb2.setBounds(72, 15, 50, 50);

        jb3.setContentAreaFilled(false);
        jb3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });
        jb3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb3KeyPressed(evt);
            }
        });
        PainelNumeros.add(jb3);
        jb3.setBounds(137, 16, 50, 50);

        jb4.setContentAreaFilled(false);
        jb4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });
        jb4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb4KeyPressed(evt);
            }
        });
        PainelNumeros.add(jb4);
        jb4.setBounds(14, 80, 50, 50);

        jb5.setContentAreaFilled(false);
        jb5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb5ActionPerformed(evt);
            }
        });
        jb5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb5KeyPressed(evt);
            }
        });
        PainelNumeros.add(jb5);
        jb5.setBounds(74, 80, 54, 50);

        jb6.setContentAreaFilled(false);
        jb6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb6ActionPerformed(evt);
            }
        });
        jb6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb6KeyPressed(evt);
            }
        });
        PainelNumeros.add(jb6);
        jb6.setBounds(138, 80, 50, 50);

        jb7.setContentAreaFilled(false);
        jb7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb7ActionPerformed(evt);
            }
        });
        jb7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb7KeyPressed(evt);
            }
        });
        PainelNumeros.add(jb7);
        jb7.setBounds(10, 140, 50, 50);

        jb8.setContentAreaFilled(false);
        jb8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb8ActionPerformed(evt);
            }
        });
        jb8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb8KeyPressed(evt);
            }
        });
        PainelNumeros.add(jb8);
        jb8.setBounds(80, 150, 40, 40);

        jb9.setContentAreaFilled(false);
        jb9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb9ActionPerformed(evt);
            }
        });
        jb9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb9KeyPressed(evt);
            }
        });
        PainelNumeros.add(jb9);
        jb9.setBounds(137, 144, 50, 50);

        jb0.setContentAreaFilled(false);
        jb0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb0ActionPerformed(evt);
            }
        });
        jb0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb0KeyPressed(evt);
            }
        });
        PainelNumeros.add(jb0);
        jb0.setBounds(75, 207, 54, 50);

        Sel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/BotaoSelecionadoUrna1.png"))); // NOI18N
        Sel1.setToolTipText("");
        PainelNumeros.add(Sel1);
        Sel1.setBounds(10, 10, 58, 60);

        Sel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/BotaoSelecionadoUrna1.png"))); // NOI18N
        Sel2.setToolTipText("");
        PainelNumeros.add(Sel2);
        Sel2.setBounds(72, 10, 58, 60);

        Sel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/BotaoSelecionadoUrna1.png"))); // NOI18N
        Sel3.setToolTipText("");
        PainelNumeros.add(Sel3);
        Sel3.setBounds(132, 10, 60, 60);

        Sel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/BotaoSelecionadoUrna1.png"))); // NOI18N
        Sel4.setToolTipText("");
        PainelNumeros.add(Sel4);
        Sel4.setBounds(10, 80, 60, 50);

        Sel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/BotaoSelecionadoUrna1.png"))); // NOI18N
        Sel5.setToolTipText("");
        PainelNumeros.add(Sel5);
        Sel5.setBounds(70, 80, 60, 50);

        Sel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/BotaoSelecionadoUrna1.png"))); // NOI18N
        Sel6.setToolTipText("");
        PainelNumeros.add(Sel6);
        Sel6.setBounds(132, 80, 60, 50);

        Sel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/BotaoSelecionadoUrna1.png"))); // NOI18N
        Sel7.setToolTipText("");
        PainelNumeros.add(Sel7);
        Sel7.setBounds(10, 140, 58, 60);

        Sel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/BotaoSelecionadoUrna1.png"))); // NOI18N
        Sel8.setToolTipText("");
        PainelNumeros.add(Sel8);
        Sel8.setBounds(70, 140, 60, 57);

        Sel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/BotaoSelecionadoUrna1.png"))); // NOI18N
        Sel9.setToolTipText("");
        PainelNumeros.add(Sel9);
        Sel9.setBounds(132, 137, 80, 60);

        Sel0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/BotaoSelecionadoUrna1.png"))); // NOI18N
        Sel0.setToolTipText("");
        PainelNumeros.add(Sel0);
        Sel0.setBounds(72, 200, 60, 60);

        getContentPane().add(PainelNumeros);
        PainelNumeros.setBounds(610, 100, 200, 270);

        PainelBotoes.setOpaque(false);
        PainelBotoes.setLayout(null);

        jbBranco.setContentAreaFilled(false);
        jbBranco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBrancoActionPerformed(evt);
            }
        });
        jbBranco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbBrancoKeyPressed(evt);
            }
        });
        PainelBotoes.add(jbBranco);
        jbBranco.setBounds(0, 10, 110, 50);

        jbCorrigir.setContentAreaFilled(false);
        jbCorrigir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCorrigir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCorrigirActionPerformed(evt);
            }
        });
        jbCorrigir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCorrigirKeyPressed(evt);
            }
        });
        PainelBotoes.add(jbCorrigir);
        jbCorrigir.setBounds(150, 10, 110, 50);

        jbVotar.setContentAreaFilled(false);
        jbVotar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVotarActionPerformed(evt);
            }
        });
        jbVotar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbVotarKeyPressed(evt);
            }
        });
        PainelBotoes.add(jbVotar);
        jbVotar.setBounds(286, 10, 94, 50);

        SelBr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/BotaoSelecionadoUrna3.png"))); // NOI18N
        PainelBotoes.add(SelBr);
        SelBr.setBounds(-10, 10, 120, 50);

        SelCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/BotaoSelecionadoUrna2.png"))); // NOI18N
        PainelBotoes.add(SelCor);
        SelCor.setBounds(140, 10, 120, 50);

        SelVot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/BotaoSelecionadoUrna3.png"))); // NOI18N
        PainelBotoes.add(SelVot);
        SelVot.setBounds(270, 10, 120, 50);

        getContentPane().add(PainelBotoes);
        PainelBotoes.setBounds(440, 400, 390, 70);

        lbUrna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/bg.png"))); // NOI18N
        getContentPane().add(lbUrna);
        lbUrna.setBounds(0, 0, 890, 530);

        jtfSenha.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jtfSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfSenha.setOpaque(false);
        jtfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jtfSenha);
        jtfSenha.setBounds(536, 430, 220, 50);

        lbBranco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sala_Votacao/bgBranco.png"))); // NOI18N
        getContentPane().add(lbBranco);
        lbBranco.setBounds(0, 0, 890, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSenhaKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            confirmar();
        }
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jtfSenhaKeyPressed

    private void jbCorrigirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCorrigirActionPerformed
        CorrigirVoto();
        b1=true;
        verificarSelecionada();
    }//GEN-LAST:event_jbCorrigirActionPerformed

    private void jbVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVotarActionPerformed
        String c = jtfCod.getText();
        if(c.equalsIgnoreCase("")){
            Object[] options = { "Sim", "Não" };
                    int opcao = JOptionPane.showOptionDialog(null, "Nenhum número encontrado, deseja votar nulo?", "JKLR Sistemas", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,options[0]);
                        if (opcao==0) {
                            votarNulo();
                            bVotar=true;
                            verificarSelecionada();
                        } else {
                            CorrigirVoto();
                            b1=true;
                            verificarSelecionada();
                        }
        }else{
           ConfirmarVoto();
           bVotar=true;
           verificarSelecionada();
        }   
    }//GEN-LAST:event_jbVotarActionPerformed

    private void jbVotarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbVotarKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String c = jtfCod.getText();
            if(c.equalsIgnoreCase("")){
                Object[] options = { "Sim", "Não" };
                        int opcao = JOptionPane.showOptionDialog(null, "Nenhum número encontrado, deseja votar nulo?", "JKLR Sistemas", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,options[0]);
                            if (opcao==0) {
                                votarNulo();
                                b1=true;
                                verificarSelecionada();
                            } else {
                                CorrigirVoto();
                                b1=true;
                                verificarSelecionada();
                                
                            }
            }else{
                ConfirmarVoto();
                b1=true;
                verificarSelecionada();
            } 
        }
        if(evt.getKeyCode()== KeyEvent.VK_UP){
            jb0.requestFocus();
            b0=true;
            verificarSelecionada();
            
        }
        if(evt.getKeyCode()== KeyEvent.VK_LEFT){
            jbCorrigir.requestFocus();
            bCorrigir=true;
            verificarSelecionada();
        }
        
        //----------------------------------------------------------------------
        
        if(evt.getKeyCode()== KeyEvent.VK_1){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "1"); 
                procurarCandidato();   
            }   
        }//Se 1
        
        if(evt.getKeyCode()== KeyEvent.VK_2){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "2"); 
                procurarCandidato();   
            }   
        }//Se 2
        
        if(evt.getKeyCode()== KeyEvent.VK_3){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "3"); 
                procurarCandidato();   
            }   
        }//Se 3
        
        if(evt.getKeyCode()== KeyEvent.VK_4){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "4"); 
                procurarCandidato();   
            }   
        }//Se 4
        
        if(evt.getKeyCode()== KeyEvent.VK_5){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "5"); 
                procurarCandidato();   
            }   
        }//Se 5
        
        if(evt.getKeyCode()== KeyEvent.VK_6){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "6"); 
                procurarCandidato();   
            }   
        }//Se 6
        
        if(evt.getKeyCode()== KeyEvent.VK_7){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "7"); 
                procurarCandidato();   
            }   
        }//Se 7
        
        if(evt.getKeyCode()== KeyEvent.VK_8){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "8"); 
                procurarCandidato();   
            }   
        }//Se 8
        
        if(evt.getKeyCode()== KeyEvent.VK_9){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "9"); 
                procurarCandidato();   
            }   
        }//Se 9
        
        if(evt.getKeyCode()== KeyEvent.VK_0){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "0"); 
                procurarCandidato();   
            }   
        }//Se 0
        
    }//GEN-LAST:event_jbVotarKeyPressed

    private void jbCorrigirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCorrigirKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            CorrigirVoto();
            b1=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_RIGHT){
            jbVotar.requestFocus();
            bVotar=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_LEFT){
            jbBranco.requestFocus();
            bBranco=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_UP){
            jb0.requestFocus();
            b0=true;
            verificarSelecionada();
        }
        
        //----------------------------------------------------------------------
        
        if(evt.getKeyCode()== KeyEvent.VK_1){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "1"); 
                procurarCandidato();   
            }   
        }//Se 1
        
        if(evt.getKeyCode()== KeyEvent.VK_2){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "2"); 
                procurarCandidato();   
            }   
        }//Se 2
        
        if(evt.getKeyCode()== KeyEvent.VK_3){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "3"); 
                procurarCandidato();   
            }   
        }//Se 3
        
        if(evt.getKeyCode()== KeyEvent.VK_4){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "4"); 
                procurarCandidato();   
            }   
        }//Se 4
        
        if(evt.getKeyCode()== KeyEvent.VK_5){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "5"); 
                procurarCandidato();   
            }   
        }//Se 5
        
        if(evt.getKeyCode()== KeyEvent.VK_6){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "6"); 
                procurarCandidato();   
            }   
        }//Se 6
        
        if(evt.getKeyCode()== KeyEvent.VK_7){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "7"); 
                procurarCandidato();   
            }   
        }//Se 7
        
        if(evt.getKeyCode()== KeyEvent.VK_8){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "8"); 
                procurarCandidato();   
            }   
        }//Se 8
        
        if(evt.getKeyCode()== KeyEvent.VK_9){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "9"); 
                procurarCandidato();   
            }   
        }//Se 9
        
        if(evt.getKeyCode()== KeyEvent.VK_0){
            String c = jtfCod.getText();
            if(c.length()>2){
                
            }else{
              jtfCod.setText(c + "0"); 
                procurarCandidato();   
            }   
        }//Se 0
        
    }//GEN-LAST:event_jbCorrigirKeyPressed

    private void jb0KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb0KeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "0");
                procurarCandidato();
            }
        }
        if(evt.getKeyCode()== KeyEvent.VK_UP){
            jb8.requestFocus();
            b8=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_DOWN){
            jbVotar.requestFocus();
            bVotar=true;
            verificarSelecionada();
        }

        //----------------------------------------------------------------------

        if(evt.getKeyCode()== KeyEvent.VK_1){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "1");
                procurarCandidato();
            }
        }//Se 1

        if(evt.getKeyCode()== KeyEvent.VK_2){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "2");
                procurarCandidato();
            }
        }//Se 2

        if(evt.getKeyCode()== KeyEvent.VK_3){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "3");
                procurarCandidato();
            }
        }//Se 3

        if(evt.getKeyCode()== KeyEvent.VK_4){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "4");
                procurarCandidato();
            }
        }//Se 4

        if(evt.getKeyCode()== KeyEvent.VK_5){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "5");
                procurarCandidato();
            }
        }//Se 5

        if(evt.getKeyCode()== KeyEvent.VK_6){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "6");
                procurarCandidato();
            }
        }//Se 6

        if(evt.getKeyCode()== KeyEvent.VK_7){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "7");
                procurarCandidato();
            }
        }//Se 7

        if(evt.getKeyCode()== KeyEvent.VK_8){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "8");
                procurarCandidato();
            }
        }//Se 8

        if(evt.getKeyCode()== KeyEvent.VK_9){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "9");
                procurarCandidato();
            }
        }//Se 9

        if(evt.getKeyCode()== KeyEvent.VK_0){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "0");
                procurarCandidato();
            }
        }//Se 0

    }//GEN-LAST:event_jb0KeyPressed

    private void jb0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb0ActionPerformed
        String c = jtfCod.getText();
        if(c.length()>2){

        }else{
            jtfCod.setText(c + "0");
            procurarCandidato();
            b0=true;
            verificarSelecionada();
        }
    }//GEN-LAST:event_jb0ActionPerformed

    private void jb9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb9KeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "9");
                procurarCandidato();
            }
        }

        if(evt.getKeyCode()== KeyEvent.VK_LEFT){
            jb8.requestFocus();
            b8=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_UP){
            jb6.requestFocus();
            b6=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_DOWN){
            jbVotar.requestFocus();
            bVotar=true;
            verificarSelecionada();
        }
        
        //----------------------------------------------------------------------

        if(evt.getKeyCode()== KeyEvent.VK_1){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "1");
                procurarCandidato();
            }
        }//Se 1

        if(evt.getKeyCode()== KeyEvent.VK_2){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "2");
                procurarCandidato();
            }
        }//Se 2

        if(evt.getKeyCode()== KeyEvent.VK_3){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "3");
                procurarCandidato();
            }
        }//Se 3

        if(evt.getKeyCode()== KeyEvent.VK_4){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "4");
                procurarCandidato();
            }
        }//Se 4

        if(evt.getKeyCode()== KeyEvent.VK_5){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "5");
                procurarCandidato();
            }
        }//Se 5

        if(evt.getKeyCode()== KeyEvent.VK_6){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "6");
                procurarCandidato();
            }
        }//Se 6

        if(evt.getKeyCode()== KeyEvent.VK_7){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "7");
                procurarCandidato();
            }
        }//Se 7

        if(evt.getKeyCode()== KeyEvent.VK_8){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "8");
                procurarCandidato();
            }
        }//Se 8

        if(evt.getKeyCode()== KeyEvent.VK_9){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "9");
                procurarCandidato();
            }
        }//Se 9

        if(evt.getKeyCode()== KeyEvent.VK_0){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "0");
                procurarCandidato();
            }
        }//Se 0

    }//GEN-LAST:event_jb9KeyPressed

    private void jb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb9ActionPerformed
        String c = jtfCod.getText();
        if(c.length()>2){

        }else{
            jtfCod.setText(c + "9");
            procurarCandidato();
            b9=true;
            verificarSelecionada();
        }
    }//GEN-LAST:event_jb9ActionPerformed

    private void jb8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb8KeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "8");
                procurarCandidato();
            }
        }
        if(evt.getKeyCode()== KeyEvent.VK_RIGHT){
            jb9.requestFocus();
            b9=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_LEFT){
            jb7.requestFocus();
            b7=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_UP){
            jb5.requestFocus();
            b5=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_DOWN){
            jb0.requestFocus();
            b0=true;
            verificarSelecionada();
        }

        //----------------------------------------------------------------------

        if(evt.getKeyCode()== KeyEvent.VK_1){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "1");
                procurarCandidato();
            }
        }//Se 1

        if(evt.getKeyCode()== KeyEvent.VK_2){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "2");
                procurarCandidato();
            }
        }//Se 2

        if(evt.getKeyCode()== KeyEvent.VK_3){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "3");
                procurarCandidato();
            }
        }//Se 3

        if(evt.getKeyCode()== KeyEvent.VK_4){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "4");
                procurarCandidato();
            }
        }//Se 4

        if(evt.getKeyCode()== KeyEvent.VK_5){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "5");
                procurarCandidato();
            }
        }//Se 5

        if(evt.getKeyCode()== KeyEvent.VK_6){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "6");
                procurarCandidato();
            }
        }//Se 6

        if(evt.getKeyCode()== KeyEvent.VK_7){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "7");
                procurarCandidato();
            }
        }//Se 7

        if(evt.getKeyCode()== KeyEvent.VK_8){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "8");
                procurarCandidato();
            }
        }//Se 8

        if(evt.getKeyCode()== KeyEvent.VK_9){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "9");
                procurarCandidato();
            }
        }//Se 9

        if(evt.getKeyCode()== KeyEvent.VK_0){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "0");
                procurarCandidato();
            }
        }//Se 0

    }//GEN-LAST:event_jb8KeyPressed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        String c = jtfCod.getText();
        if(c.length()>2){

        }else{
            jtfCod.setText(c + "8");
            procurarCandidato();
            b8=true;
            verificarSelecionada();
        }
    }//GEN-LAST:event_jb8ActionPerformed

    private void jb7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb7KeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "7");
                procurarCandidato();
            }
        }
        if(evt.getKeyCode()== KeyEvent.VK_RIGHT){
            jb8.requestFocus();
            b8=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_UP){
            jb4.requestFocus();
            b4=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_DOWN){
            jbCorrigir.requestFocus();
            bCorrigir=true;
            verificarSelecionada();
        }

        //----------------------------------------------------------------------

        if(evt.getKeyCode()== KeyEvent.VK_1){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "1");
                procurarCandidato();
            }
        }//Se 1

        if(evt.getKeyCode()== KeyEvent.VK_2){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "2");
                procurarCandidato();
            }
        }//Se 2

        if(evt.getKeyCode()== KeyEvent.VK_3){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "3");
                procurarCandidato();
            }
        }//Se 3

        if(evt.getKeyCode()== KeyEvent.VK_4){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "4");
                procurarCandidato();
            }
        }//Se 4

        if(evt.getKeyCode()== KeyEvent.VK_5){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "5");
                procurarCandidato();
            }
        }//Se 5

        if(evt.getKeyCode()== KeyEvent.VK_6){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "6");
                procurarCandidato();
            }
        }//Se 6

        if(evt.getKeyCode()== KeyEvent.VK_7){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "7");
                procurarCandidato();
            }
        }//Se 7

        if(evt.getKeyCode()== KeyEvent.VK_8){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "8");
                procurarCandidato();
            }
        }//Se 8

        if(evt.getKeyCode()== KeyEvent.VK_9){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "9");
                procurarCandidato();
            }
        }//Se 9

        if(evt.getKeyCode()== KeyEvent.VK_0){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "0");
                procurarCandidato();
            }
        }//Se 0

    }//GEN-LAST:event_jb7KeyPressed

    private void jb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb7ActionPerformed
        String c = jtfCod.getText();
        if(c.length()>2){

        }else{
            jtfCod.setText(c + "7");
            procurarCandidato();
            b7=true;
            verificarSelecionada();
        }
    }//GEN-LAST:event_jb7ActionPerformed

    private void jb6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb6KeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "6");
                procurarCandidato();
            }
        }
        if(evt.getKeyCode()== KeyEvent.VK_LEFT){
            jb5.requestFocus();
            b5=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_UP){
            jb3.requestFocus();
            b3=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_DOWN){
            jb9.requestFocus();
            b9=true;
            verificarSelecionada();
        }

        //----------------------------------------------------------------------

        if(evt.getKeyCode()== KeyEvent.VK_1){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "1");
                procurarCandidato();
            }
        }//Se 1

        if(evt.getKeyCode()== KeyEvent.VK_2){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "2");
                procurarCandidato();
            }
        }//Se 2

        if(evt.getKeyCode()== KeyEvent.VK_3){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "3");
                procurarCandidato();
            }
        }//Se 3

        if(evt.getKeyCode()== KeyEvent.VK_4){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "4");
                procurarCandidato();
            }
        }//Se 4

        if(evt.getKeyCode()== KeyEvent.VK_5){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "5");
                procurarCandidato();
            }
        }//Se 5

        if(evt.getKeyCode()== KeyEvent.VK_6){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "6");
                procurarCandidato();
            }
        }//Se 6

        if(evt.getKeyCode()== KeyEvent.VK_7){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "7");
                procurarCandidato();
            }
        }//Se 7

        if(evt.getKeyCode()== KeyEvent.VK_8){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "8");
                procurarCandidato();
            }
        }//Se 8

        if(evt.getKeyCode()== KeyEvent.VK_9){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "9");
                procurarCandidato();
            }
        }//Se 9

        if(evt.getKeyCode()== KeyEvent.VK_0){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "0");
                procurarCandidato();
            }
        }//Se 0

    }//GEN-LAST:event_jb6KeyPressed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        String c = jtfCod.getText();
        if(c.length()>2){

        }else{
            jtfCod.setText(c + "6");
            procurarCandidato();
            b6=true;
            verificarSelecionada();
        }
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb5KeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "5");
                procurarCandidato();
            }
        }
        if(evt.getKeyCode()== KeyEvent.VK_RIGHT){
            jb6.requestFocus();
            b6=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_UP){
            jb2.requestFocus();
            b2=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_LEFT){
            jb4.requestFocus();
            b4=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_DOWN){
            jb8.requestFocus();
            b8=true;
            verificarSelecionada();
        }

        //----------------------------------------------------------------------

        if(evt.getKeyCode()== KeyEvent.VK_1){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "1");
                procurarCandidato();
            }
        }//Se 1

        if(evt.getKeyCode()== KeyEvent.VK_2){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "2");
                procurarCandidato();
            }
        }//Se 2

        if(evt.getKeyCode()== KeyEvent.VK_3){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "3");
                procurarCandidato();
            }
        }//Se 3

        if(evt.getKeyCode()== KeyEvent.VK_4){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "4");
                procurarCandidato();
            }
        }//Se 4

        if(evt.getKeyCode()== KeyEvent.VK_5){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "5");
                procurarCandidato();
            }
        }//Se 5

        if(evt.getKeyCode()== KeyEvent.VK_6){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "6");
                procurarCandidato();
            }
        }//Se 6

        if(evt.getKeyCode()== KeyEvent.VK_7){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "7");
                procurarCandidato();
            }
        }//Se 7

        if(evt.getKeyCode()== KeyEvent.VK_8){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "8");
                procurarCandidato();
            }
        }//Se 8

        if(evt.getKeyCode()== KeyEvent.VK_9){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "9");
                procurarCandidato();
            }
        }//Se 9

        if(evt.getKeyCode()== KeyEvent.VK_0){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "0");
                procurarCandidato();
            }
        }//Se 0

    }//GEN-LAST:event_jb5KeyPressed

    private void jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb5ActionPerformed
        String c = jtfCod.getText();
        if(c.length()>2){

        }else{
            jtfCod.setText(c + "5");
            procurarCandidato();
            b5=true;
            verificarSelecionada();
        }
    }//GEN-LAST:event_jb5ActionPerformed

    private void jb4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb4KeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "4");
                procurarCandidato();
            }
        }
        if(evt.getKeyCode()== KeyEvent.VK_RIGHT){
            jb5.requestFocus();
            b5=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_UP){
            jb1.requestFocus();
            b1=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_DOWN){
            jb7.requestFocus();
            b7=true;
            verificarSelecionada();
        }

        //----------------------------------------------------------------------

        if(evt.getKeyCode()== KeyEvent.VK_1){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "1");
                procurarCandidato();
            }
        }//Se 1

        if(evt.getKeyCode()== KeyEvent.VK_2){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "2");
                procurarCandidato();
            }
        }//Se 2

        if(evt.getKeyCode()== KeyEvent.VK_3){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "3");
                procurarCandidato();
            }
        }//Se 3

        if(evt.getKeyCode()== KeyEvent.VK_4){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "4");
                procurarCandidato();
            }
        }//Se 4

        if(evt.getKeyCode()== KeyEvent.VK_5){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "5");
                procurarCandidato();
            }
        }//Se 5

        if(evt.getKeyCode()== KeyEvent.VK_6){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "6");
                procurarCandidato();
            }
        }//Se 6

        if(evt.getKeyCode()== KeyEvent.VK_7){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "7");
                procurarCandidato();
            }
        }//Se 7

        if(evt.getKeyCode()== KeyEvent.VK_8){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "8");
                procurarCandidato();
            }
        }//Se 8

        if(evt.getKeyCode()== KeyEvent.VK_9){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "9");
                procurarCandidato();
            }
        }//Se 9

        if(evt.getKeyCode()== KeyEvent.VK_0){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "0");
                procurarCandidato();
            }
        }//Se 0

    }//GEN-LAST:event_jb4KeyPressed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        String c = jtfCod.getText();
        if(c.length()>2){

        }else{
            jtfCod.setText(c + "4");
            procurarCandidato();
            b4=true;
            verificarSelecionada();
        }
    }//GEN-LAST:event_jb4ActionPerformed

    private void jb3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb3KeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "3");
                procurarCandidato();
            }
        }
        if(evt.getKeyCode()== KeyEvent.VK_LEFT){
            jb2.requestFocus();
            b2=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_DOWN){
            jb6.requestFocus();
            b6=true;
            verificarSelecionada();
        }

        //----------------------------------------------------------------------

        if(evt.getKeyCode()== KeyEvent.VK_1){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "1");
                procurarCandidato();
            }
        }//Se 1

        if(evt.getKeyCode()== KeyEvent.VK_2){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "2");
                procurarCandidato();
            }
        }//Se 2

        if(evt.getKeyCode()== KeyEvent.VK_3){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "3");
                procurarCandidato();
            }
        }//Se 3

        if(evt.getKeyCode()== KeyEvent.VK_4){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "4");
                procurarCandidato();
            }
        }//Se 4

        if(evt.getKeyCode()== KeyEvent.VK_5){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "5");
                procurarCandidato();
            }
        }//Se 5

        if(evt.getKeyCode()== KeyEvent.VK_6){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "6");
                procurarCandidato();
            }
        }//Se 6

        if(evt.getKeyCode()== KeyEvent.VK_7){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "7");
                procurarCandidato();
            }
        }//Se 7

        if(evt.getKeyCode()== KeyEvent.VK_8){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "8");
                procurarCandidato();
            }
        }//Se 8

        if(evt.getKeyCode()== KeyEvent.VK_9){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "9");
                procurarCandidato();
            }
        }//Se 9

        if(evt.getKeyCode()== KeyEvent.VK_0){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "0");
                procurarCandidato();
            }
        }//Se 0

    }//GEN-LAST:event_jb3KeyPressed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        String c = jtfCod.getText();
        if(c.length()>2){

        }else{
            jtfCod.setText(c + "3");
            procurarCandidato();
            b3=true;
            verificarSelecionada();
        }
    }//GEN-LAST:event_jb3ActionPerformed

    private void jb2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb2KeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "2");
                procurarCandidato();
            }
        }
        if(evt.getKeyCode()== KeyEvent.VK_RIGHT){
            jb3.requestFocus();
            b3=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_LEFT){
            jb1.requestFocus();
            b1=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_DOWN){
            jb5.requestFocus();
            b5=true;
            verificarSelecionada();
        }

        //----------------------------------------------------------------------

        if(evt.getKeyCode()== KeyEvent.VK_1){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "1");
                procurarCandidato();
            }
        }//Se 1

        if(evt.getKeyCode()== KeyEvent.VK_2){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "2");
                procurarCandidato();
            }
        }//Se 2

        if(evt.getKeyCode()== KeyEvent.VK_3){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "3");
                procurarCandidato();
            }
        }//Se 3

        if(evt.getKeyCode()== KeyEvent.VK_4){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "4");
                procurarCandidato();
            }
        }//Se 4

        if(evt.getKeyCode()== KeyEvent.VK_5){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "5");
                procurarCandidato();
            }
        }//Se 5

        if(evt.getKeyCode()== KeyEvent.VK_6){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "6");
                procurarCandidato();
            }
        }//Se 6

        if(evt.getKeyCode()== KeyEvent.VK_7){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "7");
                procurarCandidato();
            }
        }//Se 7

        if(evt.getKeyCode()== KeyEvent.VK_8){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "8");
                procurarCandidato();
            }
        }//Se 8

        if(evt.getKeyCode()== KeyEvent.VK_9){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "9");
                procurarCandidato();
            }
        }//Se 9

        if(evt.getKeyCode()== KeyEvent.VK_0){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "0");
                procurarCandidato();
            }
        }//Se 0

    }//GEN-LAST:event_jb2KeyPressed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        String c = jtfCod.getText();
        if(c.length()>2){

        }else{
            jtfCod.setText(c + "2");
            procurarCandidato();
            b2=true;
            verificarSelecionada();
        }
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb1KeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "1");
                procurarCandidato();
            }
        }
        if(evt.getKeyCode()== KeyEvent.VK_RIGHT){
            jb2.requestFocus();
            b2=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_DOWN){
            jb4.requestFocus();
            b4=true;
            verificarSelecionada();
        }

        //----------------------------------------------------------------------

        if(evt.getKeyCode()== KeyEvent.VK_1){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "1");
                procurarCandidato();
            }
        }//Se 1

        if(evt.getKeyCode()== KeyEvent.VK_2){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "2");
                procurarCandidato();
            }
        }//Se 2

        if(evt.getKeyCode()== KeyEvent.VK_3){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "3");
                procurarCandidato();
            }
        }//Se 3

        if(evt.getKeyCode()== KeyEvent.VK_4){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "4");
                procurarCandidato();
            }
        }//Se 4

        if(evt.getKeyCode()== KeyEvent.VK_5){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "5");
                procurarCandidato();
            }
        }//Se 5

        if(evt.getKeyCode()== KeyEvent.VK_6){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "6");
                procurarCandidato();
            }
        }//Se 6

        if(evt.getKeyCode()== KeyEvent.VK_7){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "7");
                procurarCandidato();
            }
        }//Se 7

        if(evt.getKeyCode()== KeyEvent.VK_8){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "8");
                procurarCandidato();
            }
        }//Se 8

        if(evt.getKeyCode()== KeyEvent.VK_9){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "9");
                procurarCandidato();
            }
        }//Se 9

        if(evt.getKeyCode()== KeyEvent.VK_0){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "0");
                procurarCandidato();
            }
        }//Se 0

    }//GEN-LAST:event_jb1KeyPressed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        String c = jtfCod.getText();
        if(c.length()>2){

        }else{
            jtfCod.setText(c + "1");
            procurarCandidato();
            b1=true;
            verificarSelecionada();
        }
    }//GEN-LAST:event_jb1ActionPerformed

    private void jbBrancoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbBrancoKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }

        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            votarBranco();
            b1=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_RIGHT){
            jbCorrigir.requestFocus();
            bCorrigir=true;
            verificarSelecionada();
        }
        if(evt.getKeyCode()== KeyEvent.VK_UP){
            jb0.requestFocus();
            b0=true;
            verificarSelecionada();
        }

        //----------------------------------------------------------------------

        if(evt.getKeyCode()== KeyEvent.VK_1){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "1");
                procurarCandidato();
            }
        }//Se 1

        if(evt.getKeyCode()== KeyEvent.VK_2){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "2");
                procurarCandidato();
            }
        }//Se 2

        if(evt.getKeyCode()== KeyEvent.VK_3){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "3");
                procurarCandidato();
            }
        }//Se 3

        if(evt.getKeyCode()== KeyEvent.VK_4){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "4");
                procurarCandidato();
            }
        }//Se 4

        if(evt.getKeyCode()== KeyEvent.VK_5){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "5");
                procurarCandidato();
            }
        }//Se 5

        if(evt.getKeyCode()== KeyEvent.VK_6){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "6");
                procurarCandidato();
            }
        }//Se 6

        if(evt.getKeyCode()== KeyEvent.VK_7){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "7");
                procurarCandidato();
            }
        }//Se 7

        if(evt.getKeyCode()== KeyEvent.VK_8){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "8");
                procurarCandidato();
            }
        }//Se 8

        if(evt.getKeyCode()== KeyEvent.VK_9){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "9");
                procurarCandidato();
            }
        }//Se 9

        if(evt.getKeyCode()== KeyEvent.VK_0){
            String c = jtfCod.getText();
            if(c.length()>2){

            }else{
                jtfCod.setText(c + "0");
                procurarCandidato();
            }
        }//Se 0

    }//GEN-LAST:event_jbBrancoKeyPressed

    private void jbBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBrancoActionPerformed
        votarBranco();
        bBranco=true;
        verificarSelecionada();
    }//GEN-LAST:event_jbBrancoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel Nome;
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelDados;
    private javax.swing.JPanel PainelDados1;
    private javax.swing.JPanel PainelNumeros;
    private javax.swing.JLabel Sel0;
    private javax.swing.JLabel Sel1;
    private javax.swing.JLabel Sel2;
    private javax.swing.JLabel Sel3;
    private javax.swing.JLabel Sel4;
    private javax.swing.JLabel Sel5;
    private javax.swing.JLabel Sel6;
    private javax.swing.JLabel Sel7;
    private javax.swing.JLabel Sel8;
    private javax.swing.JLabel Sel9;
    private javax.swing.JLabel SelBr;
    private javax.swing.JLabel SelCor;
    private javax.swing.JLabel SelVot;
    private javax.swing.JButton jb0;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private javax.swing.JButton jbBranco;
    private javax.swing.JButton jbCorrigir;
    private javax.swing.JButton jbVotar;
    private javax.swing.JLabel jtfCod;
    private javax.swing.JLabel jtfNome;
    private javax.swing.JPasswordField jtfSenha;
    private javax.swing.JLabel lbBranco;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel lbUrna;
    // End of variables declaration//GEN-END:variables

    private void confirmar() {
        String cod = jtfSenha.getText();
        Connection con = Conexao.abrirConexao();
        AdminDAO sql = new AdminDAO(con);
            if(cod.equals("")){
                JOptionPane.showMessageDialog(null, "Você não digitou nenhuma senha.", "JKLR Sistemas", JOptionPane.WARNING_MESSAGE);
            }else{
                    if(sql.VerificarSenha(cod)==false){
                        JOptionPane.showMessageDialog(null, "Senha incorreta, tente novamente.", "JKLR Sistemas", JOptionPane.WARNING_MESSAGE);
                        jtfSenha.setText("");
                    }else{
                        InserirVotacao();
                        jtfSenha.setText("");
                        jb1.requestFocus();
                    }
                
            }
        Conexao.fecharConexao(con);    
    }

    private void InserirVotacao() {
        jtfSenha.setVisible(false);
        lbBranco.setVisible(false);
        lbUrna.setVisible(true);
        PainelBotoes.setVisible(true);
        PainelDados.setVisible(true);
        PainelDados1.setVisible(true);
        PainelNumeros.setVisible(true);
        lbFoto.setVisible(true);

        b1=true;
        verificarSelecionada();
    }

    private void limparVotacao() {
        lbBranco.setVisible(true);
        jtfSenha.setVisible(true);
        lbUrna.setVisible(false);
        PainelBotoes.setVisible(false);
        PainelDados.setVisible(false);
        PainelDados1.setVisible(false);
        PainelNumeros.setVisible(false);
        lbFoto.setIcon(null);
        lbFoto.setVisible(false);
        jtfNome.setText("");
        jtfCod.setText("");
    }
    
    private void procurarCandidato(){
        String cod = jtfCod.getText();
        Connection con = Conexao.abrirConexao();
        CandidatoDAO sql = new CandidatoDAO(con);
        int matricula = Integer.parseInt(cod);
            if(sql.TestarCandidato(matricula)==true){
                limparCampos();
                InserirDados(matricula);
            }
        Conexao.fecharConexao(con);
    }

    private void limparCampos(){
        jtfNome.setText("");
        jtfCod.setText("");
        lbFoto.setIcon(null);
    }
    
    private void InserirDados(int cod) {
        Connection con = Conexao.abrirConexao();
        CandidatoDAO sql = new CandidatoDAO(con);
        List<Candidato> lista = new ArrayList<>();
        lista = sql.buscarCandidato(cod);
        
            for(Candidato a : lista){
                jtfCod.setText("" + a.getCod_candidato());
                jtfNome.setText("" + a.getNome());
                String url = a.getFoto();
                this.path = url;
                colocarFoto(url);
            }
        Conexao.fecharConexao(con);
    }
    
    private void colocarFoto(String url) {
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(url).getImage().getScaledInstance(lbFoto.getWidth(), lbFoto.getHeight(), Image.SCALE_DEFAULT));
        lbFoto.setIcon(imageIcon);
    }
    
    //--------------------------------------------------------------------------
    
    private void votarBranco() {
        Eleicao a = new Eleicao();
        Connection con = Conexao.abrirConexao();
        EleicaoDAO adao = new EleicaoDAO(con);
        int cod = adao.verificarEleicao();
        System.out.println("Codigo da eleição:(brancos) "+cod);
            if(cod!=0){
                int brancos = adao.verificarBrancos(cod);
                System.out.println("Quantos votos brancos: "+brancos);
                a.setNum_eleicao(cod);
                a.setBrancos(brancos);
                adao.votarBranco(a);
                som();
                limparVotacao();
                Conexao.fecharConexao(con);
            }else{
                this.dispose();
                JOptionPane.showMessageDialog(null, "Nenhuma eleição encontrada, encerre a atual e tente novamente.","JKLR Sistemas",JOptionPane.PLAIN_MESSAGE);
            }
        
    }

    private void CorrigirVoto() {
        jtfCod.setText("");
        jtfNome.setText("");
        lbFoto.setIcon(null);
        
        jb1.requestFocus();
    }

    private void ConfirmarVoto() {
        Connection con = Conexao.abrirConexao();
        CandidatoDAO sql = new CandidatoDAO(con);
        EleicaoDAO adao = new EleicaoDAO(con);
        int cod = adao.verificarEleicao();
        System.out.println("Codigo da eleição:(ConfirmarVoto) "+cod);
            if(cod!=0){
                int codCandidato = Integer.parseInt(jtfCod.getText());
                System.out.println("Código candidato(JIVotar):"+codCandidato);
                boolean v = sql.TestarCandidato(codCandidato);
                System.out.println("Boolean testarCandidato(JinternalVotar):"+v);
                if (v==true) {
                    votarCandidato();
                }else{
                    Object[] options = { "Sim", "Não" };
                    int opcao = JOptionPane.showOptionDialog(null, "Candidato não encontrado, deseja votar nulo?", "JKLR Sistemas", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,options[0]);
                        if (opcao==0) {
                            votarNulo();
                        } else {
                            CorrigirVoto();
                        }
                }
            }else{
                this.dispose();
                JOptionPane.showMessageDialog(null, "Nenhuma eleição encontrada, encerre a atual e tente novamente.","JKLR Sistemas",JOptionPane.PLAIN_MESSAGE);
            }
                
    }

    private void votarNulo() {
        Eleicao a = new Eleicao();
        Connection con = Conexao.abrirConexao();
        EleicaoDAO adao = new EleicaoDAO(con);
        int cod = adao.verificarEleicao();
        System.out.println("Codigo da eleição(nulos): "+cod);
            if(cod!=0){
                int nulos = adao.verificarNulos(cod);
                System.out.println("Quantos votos nulos: "+nulos);
                a.setNum_eleicao(cod);
                a.setNulos(nulos);
                adao.votarNulo(a);                
                som();
                limparVotacao();
                Conexao.fecharConexao(con);
            }else{
                this.dispose();
                JOptionPane.showMessageDialog(null, "Nenhuma eleição encontrada, encerre a atual e tente novamente.","JKLR Sistemas",JOptionPane.PLAIN_MESSAGE);
                
            }

    }
    
    private void votarCandidato(){
        Eleicao a = new Eleicao();
        Candidato b = new Candidato();
        Connection con = Conexao.abrirConexao();
        EleicaoDAO adao = new EleicaoDAO(con);
        CandidatoDAO sql = new CandidatoDAO(con);
        int cod = adao.verificarEleicao();
        System.out.println("Codigo da eleição:(Candidato) "+cod);
            if(cod!=0){
                int codCand = Integer.parseInt(jtfCod.getText());
                int codCandidato = sql.SelecionarCodCandidato(codCand);
                System.out.println("Código candidato: "+codCandidato);
                int votos = sql.verificarVotos(codCandidato);
                System.out.println("Quantos votos no candidato: "+votos);
                b.setCod_candidato(codCandidato);
                b.setVotos(votos);
                sql.votar(b);
                
                int validos = sql.verificarValidos(cod);
                System.out.println("Verificar a quantidade de votos válidos(JIVotar):"+validos);
                
                a.setNum_eleicao(cod);
                a.setValidos(validos);
                
                String r = sql.addValido(a);
                System.out.println("Adicionou válidos?(JIVotar):"+r);
                som();
                limparVotacao();
                Conexao.fecharConexao(con);
            }else{
                this.dispose();
                JOptionPane.showMessageDialog(null, "Nenhuma eleição encontrada, encerre a atual e tente novamente.","JKLR Sistemas",JOptionPane.PLAIN_MESSAGE);
            }
    }

    //--------------------------------------------------------------------------
    
    private void verificarSelecionada() {
        Sel0.setVisible(false);
        Sel1.setVisible(false);
        Sel2.setVisible(false);
        Sel3.setVisible(false);
        Sel4.setVisible(false);
        Sel5.setVisible(false);
        Sel6.setVisible(false);
        Sel7.setVisible(false);
        Sel8.setVisible(false);
        Sel9.setVisible(false);
        SelCor.setVisible(false);
        SelVot.setVisible(false);
        SelBr.setVisible(false);
        
        if(b1==true){
            Sel1.setVisible(true);
        }else if(b2==true){
            Sel2.setVisible(true);
        }else if(b3==true){
            Sel3.setVisible(true);
        }else if(b4==true){
            Sel4.setVisible(true);
        }else if(b5==true){
            Sel5.setVisible(true);
        }else if(b6==true){
            Sel6.setVisible(true);
        }else if(b7==true){
            Sel7.setVisible(true);
        }else if(b8==true){
            Sel8.setVisible(true);
        }else if(b8==true){
            Sel8.setVisible(true);
        }else if(b9==true){
            Sel9.setVisible(true);
        }else if(b0==true){
            Sel0.setVisible(true);
        }else if(bVotar==true){
            SelVot.setVisible(true);
        }else if(bCorrigir==true){
            SelCor.setVisible(true);
        }else if(bBranco==true){
            SelBr.setVisible(true);
        }                             

        bBranco=false;
        bCorrigir=false;
        bVotar=false;
        b1=false;
        b2=false;
        b3=false;
        b4=false;
        b5=false;
        b6=false;
        b7=false;
        b8=false;
        b9=false;
        b0=false;
        
    }

    private void som() {
        try {
            audio.play();
            Thread.sleep(sono);
        } catch (Exception e) {
            e.getMessage();
        }
    }
    
}
